# Generated by Django 2.2.5 on 2021-02-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='firstName',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='author',
            name='lastName',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
