# Generated by Django 2.2.5 on 2021-02-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20210202_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
